spring:
  application:
    name: chat
  config:
    import: optional:file:../local-config.yaml,optional:file:./local-config.yaml
  ai:
    openai:
      api-key: ${deepseek.api-key}
      base-url: ${deepseek.base-url}
      chat:
        model: ${deepseek.chat-model}
server:
  port: 8096
springdoc:
  # Swagger UI 界面配置
  swagger-ui:
    enabled: true # 是否启用UI，生产环境可关闭
    path: /swagger-ui.html # UI访问路径
  # OpenAPI 规范JSON配置
  api-docs:
    enabled: true # 是否启用JSON端点，生产环境可关闭
    path: /v3/api-docs # JSON数据访问路径
  # 可选：指定扫描的包路径，缩小文档范围
  packages-to-scan: org.aeryzhao
  # 可选：全局设置默认的请求/响应类型
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
