server:
  port: 8080

spring:
  application:
    name: rag-project

  config:
    import: optional:file:../local-config.yaml,optional:file:./local-config.yaml

  ai:
    model:
      chat: openai
      embedding: ollama

    openai:
      api-key: ${deepseek.api-key}
      base-url: ${deepseek.base-url}
      chat:
        model: ${deepseek.chat-model}
        temperature: 0.7

    ollama:
      base-url: ${ollama.base-url:http://127.0.0.1:11434}
      embedding:
        model: ${ollama.embedding-model:qwen3-embedding}

    vectorstore:
      type: milvus
      milvus:
        client:
          uri: http://localhost:19530
        collection-name: rag_documents
        index-type: IVF_FLAT
        metric-type: COSINE
        embedding-dimension: 4096
        initialize-schema: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

rag:
  document:
    chunk-size: 2000
